version: "3.0"
services:
  db1:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres2
    ports:
      - "5432:5432"
    networks:
      - custom

  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    ports:
      - "6000:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
